version: 2.1
jobs:
  test:
    docker:
      - image: cimg/node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
      - run:
          name: install packages
          command: yarn
      - run:
          name: installing Heroku CLI
          command: yarn add -ED heroku
      - save_cache:
          key: node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
          paths:
            - ~/.yarn
      - run:
          name: Run Tests
          command: yarn run lint
      - run:
          name: Logging into Heroku Containers
          command: yarn run heroku container:login
      - run:
          name: Building and pushing docker image to Heroku Containers
          command: yarn run  heroku container:push web -a=helpertux
      - run:
          name: Updating HelperTux
          command: yarn run heroku container:release web -a=helpertux
workflows:
  orb-free-workflow:
    jobs:
      - test
